import {
  createAgentChatPlugin,
  loadActionsFromStaticRegistry,
} from "@agent-native/core/server";
import { getOrgContext } from "@agent-native/core/org";

// Static-import registry generated by @agent-native/core's Vite plugin at
// build time. Using a static import ensures bundlers include every action
// module in the server bundle — a runtime filesystem scan finds nothing in a
// bundled function, which is why `autoDiscoverActions` on its own produces
// 404s for action routes in production.
import actionsRegistry from "../../.generated/actions-registry.js";

/**
 * Tools loaded up front for every chat turn. Keep this list short: everything
 * else in `actions/` stays discoverable through tool-search.
 */
const INITIAL_TOOL_NAMES = ["view-screen", "navigate", "hello"];

export default createAgentChatPlugin({
  appId: "agent-native-workshop",
  initialToolNames: INITIAL_TOOL_NAMES,
  resolveOrgId: async (event) => {
    const ctx = await getOrgContext(event);
    return ctx.orgId;
  },
  actions: loadActionsFromStaticRegistry(actionsRegistry),
  systemPrompt: `You are the assistant for this app. It is a fresh agent-native skeleton — there is one example action and one screen so far.

Some less-common tool schemas are loaded on demand. Use tool-search with a specific query when you need a capability that is not already available as a direct tool.

## Use Actions
- \`pnpm action view-screen\` — See what the user is looking at (current view).
- \`pnpm action navigate --view home|settings\` — Move the UI. When the user says "show me", "go to", or "open", navigate first, then answer.
- \`pnpm action hello --name "Ada"\` — The example greeting action.

## Context Awareness
The UI writes its current view to the \`navigation\` application-state key. Call view-screen when the answer depends on that visible state; skip it for questions that do not.

As this app grows, every user-facing operation should become an action so the UI and the agent stay on one contract.`,
});
